### ISSUE TITLE
Hide link if user doesn't have permission

### ISSUE THREAD

**Issue by x7airworker** [FriendsOfFlarum/links#18]
A Flarum link should hide, if the user doesn't have permission to the tag the discussion belongs to.

**Comment by datitisev** [comment]
Problem with this is that links by themselves do _not_ have permissions - it's the content they show. You are simply setting an address to the link - there's not much permission checking you can do there.

Perhaps if we use the config.php URL and find the resource that way, but that won't always work. Will probably have to add a feature to associate discussions/pages with links directly (instead of just putting their address).

**Comment by x7airworker** [comment]
Yeah I also thought about an implementation with links.

I think adding discussions/pages directly is the easiest solution.
