### ISSUE TITLE
Need compatibility with Beta 14

### ISSUE THREAD

**Issue by PeopleInside** [FriendsOfFlarum/links#26]
Actually miss compatibility with Beta 14
https://discuss.flarum.org/d/25184-issues-on-upgrading/2
https://github.com/PeopleInside/Flarum_Beta14_Upgrade/issues/1

**Comment by luceos** [comment]
We are well aware that some extensions aren't up to date yet. Bumping them under our noses like this isn't really civil.

Please have patience for extensions to be slowly patched, provide funding so that we can dedicate paid hours to that through donating at https://opencollective.com/fof or provide a tested Pull Request for the upgrade of this extension.

Thank you for your understanding.

**Comment by PeopleInside** [comment]
I don't have a job so I cannot donate.
I was simply try to monitor when the issue was getting resolved and it's really not nice read your message about be not civil.
I feel civil and I feel I'm not doing nothing of bad. Bad is to close an issue also if is not resolved and in this way remove the possibility to track the resolution. Don't know if you can understand on user side what this mean to be unable to upgrade Flarum and to try just to be informed when an issue is resolved. Is really this bad?
Thanks anyway.
